package ru.javamentor.EcoCRM.model.embedded;

public enum TaskType {
    PETITIONER_INFO,
    NEIGHBOURHOODS_INFO,
    OLD_CONTAINER_PHOTO,
    MANAGING_ORGANIZATION_INFO,
    CONTRACTOR_INFO,
    OFFER,
    NEW_CONTAINER_INFO,
    LEAFLETS_DESIGN,
    LEAFLETS_PRINT,
    LEAFLETS_PUBLICATION,
    RESIDENTS_ACTIVITIES,
    CASE_DESCRIPTION,
    CUSTOM
}
